#ifndef WORDCLOCK_DEFINES_H
#define WORDCLOCK_DEFINES_H

#define NUM_LEDS 114

// One hour
#define TIMEZONE_OFFSET 60 * 60

#define FULL_BRIGHTNESS 150
#define NIGHT_BRIGHTNESS 30

#endif //WORDCLOCK_DEFINES_H
